phony += flash
flash: soc-flash

soc-vendor := $(patsubst "%",%,$(CONFIG_SLAVE_SOC_VENDOR))
soc-prefix := $(patsubst "%",%,$(CONFIG_SLAVE_SOC_PREFIX))

soc-path := $(srctree)/slave/soc/$(soc-vendor)/$(soc-prefix)

slave-firmware := $(objtree)/slave/slave.hex

# минус тут нужен в случае, когда человек только клонировал
# репозиторий и у него ещё нет настроек в .config
-include $(soc-path)/Makefile.flash
