cmocka-subdir  := $(srctree)/modules/cmocka
cmocka-outdir  := $(cmocka-subdir)/out

cmocka-include := $(cmocka-subdir)/include
cmocka-libdir := $(cmocka-outdir)/src
cmocka-lib := $(cmocka-libdir)/libcmocka.so

export cflags += -I$(cmocka-include)

export ldflags += -L$(cmocka-libdir)

export libs += cmocka

# ---------------------------------------------------------

phony += tests
tests: $(cmocka-lib)
	$(q)$(MAKE) -C $(testtree)

phony += tests-master
tests-master: $(cmocka-lib)
	$(q)$(MAKE) -C $(testtree) master

phony += tests-slave
tests-slave: $(cmocka-lib)
	$(q)$(MAKE) -C $(testtree) slave


# ---------------------------------------------------------

$(cmocka-lib): $(cmocka-outdir)
	$(q)cmake -S $(cmocka-subdir) -B $(cmocka-outdir)
	$(q)cmake --build $(cmocka-outdir)

$(cmocka-outdir):
	$(q)mkdir -p $@

# ---------------------------------------------------------

phony += clean-cmocka
clean-cmocka:
	$(q)rm -rf $(cmocka-outdir)

clean-all-targets == clean-cmocka
