cmocka-subdir  := $(srctree)/modules/cmocka
cmocka-outdir  := $(cmocka-subdir)/out

export cmocka-include := $(cmocka-subdir)/include
export cmocka-libdir := $(cmocka-outdir)/src
export cmocka-lib := $(cmocka-libdir)/libcmocka.so


# ---------------------------------------------------------

phony += tests
tests: tests-master tests-slave

phony += tests-master
tests-master: dsdl $(cmocka-lib)
	$(q)rm -rf $(objtree)/tests/master
	$(q)$(MAKE) -C $(testtree) master

phony += tests-slave
tests-slave: dsdl $(cmocka-lib)
	$(q)rm -rf $(objtree)/tests/slave
	$(q)$(MAKE) -C $(testtree) slave


# ---------------------------------------------------------

$(cmocka-lib): $(cmocka-outdir)
	$(q)cmake -S $(cmocka-subdir) -B $(cmocka-outdir)
	$(q)cmake --build $(cmocka-outdir)

$(cmocka-outdir):
	$(q)mkdir -p $@

# ---------------------------------------------------------

phony += clean-cmocka
clean-cmocka:
	$(q)rm -rf $(cmocka-outdir)

clean-all-targets == clean-cmocka
