# какие переменные должны быть определены заранее перед включением этого куска:
# - local:         каталог, где лежит текущий makefile (относительно $(srctree))
# - local-srctree: каталог, в котором лежат все исходники, и относительно которого лежат
#                  префиксные каталоги, в которых тоже есть исходники
# - cflags*:       флаги компилятора
# - ldflags*:      флаги линковщика
# - libs*:         библиотеки
# - asflags*:      флаги ассемблера
# - prefix:        префикс, с котором ассоциирована цель, за которую отвечает данный Makefile
# - ld*:           линковщик, по умолчанию определён как ld
# - cc*:           компилятор, по умолчанию определён как gcc
# - asm*:          ассемблер, по умолчанию определён как gcc
# - objs:          список объектных файлов в $(objtree)/$(prefix), которые получаются после компиляции
#                  могут иметь свои дполнительные префиксы
# - target:        путь к целевому файлу (обычно это исполняемый файл расположенный под
#                  определённым префиксом в $(objtree))

# *: цели со звёздочкой необязательно переопределять, но они тоже играют свою роль

# какие переменные НЕ НАДО определять
# - gentree: определяется в корневом Makefile и указывает на generated/
# - objtree: определяется в корневом Makefile и указывает на out/


# ===============================================================


cflags += \
	-I$(gentree) -I$(srctree)/include \
	$(patsubst "%",%,$(CONFIG_OPT_LEVEL))

ifeq ($(CONFIG_SUPPRESS_WARNING),y)
	cflags += -w
else
	cflags += -Wall # -Wextra -Wpedantic
endif

ifeq ($(CONFIG_DEBUG),y)
	cflags += -g
endif

ifeq ($(CONFIG_COVERAGE),y)
	cflags += -fprofile-arcs -ftest-coverage
endif

$(objtree)/$(prefix)/%.o: $(local-srctree)/%.c
	$(q)$(cc) $(cflags) -c $^ -o $@

asflags += \
	-I$(gentree) -I$(srctree)/include \
	_D__ASSEMBLY__ \
	-Wall

$(objtree)/$(prefix)/%.o: $(local-srctree)/%.S
	$(q)$(asm) $(asflags) -a $^ -o $@


# ==============================================================

ldflags += -Wall -Wl,--check-sections -Wl,--gc-sections

$(target): $(addprefix $(objtree)/$(prefix)/, $(objs))
	$(q)$(ld) $(ldflags) $^ -o $@ $(addprefix -l, $(libs))


# ==============================================================

_objtree-prefixes := $(addprefix $(prefix)/, $(sort $(dir $(objs))))

phony += $(objtree-prefixes)
objtree-prefixes: $(_objtree-prefixes)

$(_objtree-prefixes): force
	$(q)mkdir -p $(objtree)/$@


# ==============================================================

$(gentree-prefixes): force
	$(q)mkdir -p $(gentree)/$@


# ==============================================================

phony += force
force: 
