cflags += \
	-Dprintf=iprintf \
	--param max-inline-insns-single=500 \
	-mcpu=cortex-m3 \
	-mthumb \
	-mlong-calls

asflags += \
	-mcpu-cortex-m3 \
	-mthumb

ldflags += \
	-mcpu=cortex-m3 \
	-mthumb


# -------------------------------------------

arch-time-objs-y += irq_handler.o micros.o
