#ifndef __BOULDER_COMMON_INDERNAL_VALIDATE_CONFIG
#define __BOULDER_COMMON_INDERNAL_VALIDATE_CONFIG


#include "../can.h"

#if CONFIG_CAN_BITRATE < CAN_BITRATE_MIN || CONFIG_CAN_BITRATE > CAN_BITRATE_MAX
#   error "CONFIG_CAN_BITRATE выходит за пределы допустимых значений"
#endif 


#endif // ! __BOULDER_COMMON_INDERNAL_VALIDATE_CONFIG
