#ifndef __BOULDER_SLAVE_PLATFORM_STUDICA_BLACKHAWK_H
#define __BOULDER_SLAVE_PLATFORM_STUDICA_BLACKHAWK_H


#include <slave/chips/sam3x8e.h>


#endif // ! __BOULDER_SLAVE_PLATFORM_STUDICA_BLACKHAWK_H
