soc-outdir := $(objtree)/$(slave-prefix)/$(soc-complete-prefix)

libsam := libsam_sam3x8e_gcc_rel

soc-gcc-dir := $(soc-outdir)/gcc
soc-incdir  := $(soc-outdir)/include

startup = startup_sam3xa


# -----------------------------------------------

arch-outdir := $(objtree)/$(slave-prefix)/$(arch-complete-prefix)

arch-incdir := $(arch-outdir)/include


# ------------------------------------------------

soc-outdir-targets := \
	$(soc-outdir)/$(libsam).a \
	$(soc-incdir)/libsam/include \
	$(soc-gcc-dir) \
	$(arch-incdir)


# ------------------------------------------------

# пока ArduinoCore является надёжным источником,
# откуда можно взять эту старую либу
soc-lib-url := https://github.com/arduino/ArduinoCore-sam/archive/refs/heads/master.zip

soc-zip := master.zip
soc-lib-dir := ArduinoCore-sam-master

phony += soc-prerequisites
soc-prerequisites: $(downloads)/$(soc-zip) soc-copy-targets

$(downloads)/$(soc-zip):
	$(q)curl -fSL $(soc-lib-url) -o $@

phony += soc-copy-targets
soc-copy-targets: $(soc-outdir-targets)

$(soc-outdir)/$(libsam).a: $(soc-outdir)/$(soc-lib-dir)
	$(q)cp -f $</variants/arduino_due_x/$(libsam).a $@

$(soc-incdir)/libsam/include: $(soc-outdir)/$(soc-lib-dir)
	$(q)mkdir -p $@
	$(q)cp -f $</system/libsam/include/*.h $@
	$(q)cp -f $</system/libsam/chip.h $@/..
	$(q)cp -f $</system/CMSIS/Device/ATMEL/sam*.h $@/..
	$(q)cp -rf $</system/CMSIS/Device/ATMEL/sam3xa $@/..

$(soc-outdir)/$(soc-lib-dir)/sam3xa/include: $(soc-outdir)/$(soc-lib-dir)

$(soc-gcc-dir): $(soc-outdir)/$(soc-lib-dir)
	$(q)mkdir -p $@
	$(q)cp -f $</variants/arduino_due_x/linker_scripts/gcc/*.ld $@
	$(q)cp -f $</system/CMSIS/Device/ATMEL/sam3xa/source/gcc_atmel/$(startup).c $@

$(arch-incdir): $(soc-outdir)/$(soc-lib-dir)
	$(q)mkdir -p $(arch-incdir)
	$(q)cp -f $</system/CMSIS/CMSIS/Include/core_cm3.h $(arch-incdir)
	$(q)cp -f $</system/CMSIS/CMSIS/Include/core_cmFunc.h $(arch-incdir)
	$(q)cp -f $</system/CMSIS/CMSIS/Include/core_cmInstr.h $(arch-incdir)
	$(q)cp -f $</system/CMSIS/Device/ARM/ARMCM3/Include/system_ARMCM3.h $(arch-incdir)

$(soc-outdir)/$(soc-lib-dir):
	$(q)mkdir -p $(soc-outdir)
	$(q)unzip $(downloads)/$(soc-zip) -d $(soc-outdir)


# ============================================================

phony += soc-post-build
soc-post-build: $(soc-firmware)

$(soc-firmware): $(target)
	$(q)$(objcp) -O binary $^ $@


# ============================================================

include $(archtree)/Makefile.arch


# ============================================================

# че на выходе получается
soc-can-objs-y += irq_handler.o

soc-uart-objs-y += irq_handler.o

objs += $(soc-complete-prefix)/$(startup).o

libs += $(libsam:lib%=%)

# Makefile.arch ещё че то может доабвить
soc-f := \
	-I$(soc-incdir) \
	-I$(arch-incdir) \
	-D__SAM3X8E__ \
	-I$(soc-outdir)/$(soc-lib-dir)/system/CMSIS/CMSIS/Include \
	-I$(soc-outdir)/$(soc-lib-dir)/system/CMSIS/Device/ATMEL/sam3xa/include

cflags += $(soc-f)
asflags += $(soc-f)

ldflags += \
	-L$(soc-outdir) \
	-Wl,--entry=Reset_Handler -Wl,--defsym=STACK_SIZE=$(CONFIG_STACK_SIZE)

ifeq ($(SAM3X8E_LINK_STACK_SECTION),y)
ldflags += -T $(soc-gcc-dir)/sram.ld
else
ldflags += -T $(soc-gcc-dir)/flash.ld
endif


# ============================================================

startup-o := $(objtree)/$(prefix)/$(soc-complete-prefix)/$(startup).o
startup-c := $(soc-outdir)/$(soc-lib-dir)/system/CMSIS/Device/ATMEL/sam3xa/source/gcc_atmel/$(startup).c

$(startup-o): $(startup-c)
	$(q)$(cc) -Wall $(cflags) -c $^ -o $@
