#ifndef __BOULDER_ARM_CORTEX_M3_CUSTOM_ERRORS_H
#define __BOULDER_ARM_CORTEX_M3_CUSTOM_ERRORS_H


#define ARCH_INIT_CUSTOM_ERRORS \
	ARCH_INIT_FAILED_SYSTICK_INIT


#endif // ! __BOULDER_ARM_CORTEX_M3_CUSTOM_ERRORS_H
